server:
  port: 8780
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8762/eureka/
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: user-server